name: Deploy para Locaweb via FTP

on:
  push:
    branches:
      - main   # dispara o deploy quando houver push na branch main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftp.iluminandofuturos.com.br
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html
          local-dir: ./   # pasta raiz do repositório
          exclude: |
            **/.git*
            **/.github/**
            **/.venv/**
            **/__pycache__/**
            **/tests_assets/**
            **/README.md
            **/requirements.txt
            **/*.py
            **/*.sh



